package com.questrail.wayside.protocol.genisys.internal.events;

import java.time.Instant;

/**
 * GenisysTimeoutEvent
 * -----------------------------------------------------------------------------
 * Events generated by timers within the GENISYS master state machine.
 *
 * Timers model the passage of time without blocking threads.
 */
public sealed interface GenisysTimeoutEvent extends GenisysEvent
        permits GenisysTimeoutEvent.ResponseTimeout
{
    /**
     * Indicates that the master did not receive an expected response within
     * the allowed time window.
     */
    final class ResponseTimeout extends GenisysEvent.Base implements GenisysTimeoutEvent {
        public ResponseTimeout(Instant timestamp) {
            super(timestamp);
        }
    }
}
