package com.questrail.wayside.protocol.genisys.model;

/**
 * Marker interface for all GENISYS slave → master protocol messages.
 *
 * <p>
 * These messages are generated by a slave only in response to a valid,
 * properly-addressed master request.
 * </p>
 *
 * <p>
 * GENISYS.pdf §5.1.3 is normative for the semantics of these messages.
 * </p>
 */
public sealed interface GenisysSlaveResponse extends GenisysMessage
        permits
        Acknowledge,
        IndicationData,
        ControlCheckback
{
}
